name: Update flake.lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 7 * * 2' # runs weekly on Tuesday at 00:00 PDT

permissions:
  checks: write
  contents: write
  pull-requests: write
  pages: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update system flake.lock
        if: ${{ github.event_name != 'pull_request' }}
        uses: DeterminateSystems/update-flake-lock@v24
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: update-system-flake-lock-action
          git-author-name: "Jerry Arciaga [bot]"
          git-author-email: "re6freoz@rockorsomething.anonaddy.me"
          git-committer-name: "Jerry Arciaga [bot]"
          git-committer-email: "re6freoz@rockorsomething.anonaddy.me"
          path-to-flake-dir: 'flake/'
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          pr-title: "Update system flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
          pr-assignees: jerryarciaga
          pr-reviewers: jerryarciaga
      - name: Update home manager flake.lock
        if: ${{ github.event_name != 'pull_request' }}
        uses: DeterminateSystems/update-flake-lock@v24
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: update-home-manager-flake-lock-action
          git-author-name: "Jerry Arciaga [bot]"
          git-author-email: "re6freoz@rockorsomething.anonaddy.me"
          git-committer-name: "Jerry Arciaga [bot]"
          git-committer-email: "re6freoz@rockorsomething.anonaddy.me"
          path-to-flake-dir: 'home-manager/'
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          pr-title: "Update home-manager flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
          pr-assignees: jerryarciaga
          pr-reviewers: jerryarciaga
